# 測試環境設定

# DB Connect
spring:
  datasource:
    url: ${DB_URL_TEST}
    username: ${DB_USERNAME_TEST}
    password: ${DB_PASSWORD_TEST}

qq-pos:
  jwt:
    secret-key: ${JWT_SECRET_KEY_TEST}
#    issuer: ${JWT_ISSUER_TEST}
#    audience: ${JWT_AUDIENCE_TEST}

logging:
  file:
    name: logs/qq-pos-test.log
  level:
    root: info
    com.qqriceball.mapper: debug
