# 開發環境設定
logging:
  file:
    # 開發日誌檔名
    name: logs/qq-pos-dev.log
  level:
    # 紀錄更詳細的日誌
    root: info
    com.qqriceball.mapper: debug
#    org.springframework.security: debug

qq-pos:
  jwt:
    secret-key: ${JWT_SECRET_KEY_DEV}
    cookie-secure: false
    cookie-same-site: Strict
  cors:
    allowed-origins:
        - http://localhost:3000

spring:
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}