spring:
  application:
    name: QQ-POS
  profiles:
    active: dev

  # DB Connect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

qq-pos:
  jwt:
    ttl-millis: 7200000
    token-name: Authorization


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
