# 測試環境設定

# DB Connect
spring:
  datasource:
    url: ${DB_URL_TEST}
    username: ${DB_USERNAME_TEST}
    password: ${DB_PASSWORD_TEST}

qq-pos:
  jwt:
    secret-key: ${JWT_SECRET_KEY_TEST}
    cookie-secure: false
    cookie-same-site: Strict
  cors:
    allowed-origins:
      - http://localhost:3000

logging:
  file:
    name: logs/qq-pos-test.log
  level:
    root: info
    com.qqriceball.mapper: debug
