spring:
  application:
    name: QQ-POS

  # DB Connect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

qq-pos:
  jwt:
    ttl-millis: 1200000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
