# 正式環境設定
logging:
  file:
    name: logs/qq-pos.log
  level:
    root: info

qq-pos:
  jwt:
    secret-key: ${JWT_SECRET_KEY_PROD}

spring:
  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}

# 初始化管理員帳號設定
app:
  init-admin: ${APP_INIT_ADMIN:false}
  init-admin-username: ${APP_INIT_ADMIN_USERNAME:}
  init-admin-password: ${APP_INIT_ADMIN_PASSWORD:}

server:
  forward-headers-strategy: framework